In [29]:
import numpy as np 
import matplotlib

def apGrad(f, x, h = 0.001):
    return( (f(x+h)-f(x))/h   )
    

def newton(f, x0, tol, max_iter = 100):
    xn = x0
    for n in range(0,max_iter):
        fxn = f(xn)
        if abs(fxn) < tol:
            print('Found solution after',n,'iterations.')
            return xn
        Dfxn = apGrad(f, xn)
        if Dfxn == 0:
            print('Zero derivative. No solution found.')
            return None
        xn = xn - fxn/Dfxn
    print('Exceeded maximum iterations. No solution found.')
    return None

def function_tes(x):
    return( (x-2)*(x+3)  )

def function_bad(x):
    return(x**2)

def function_superBad(x):
    return(x**5)

def function_chaos(x):
    return(x**50)

In [34]:
x = newton(function_tes, 100, 1e-06)
print(x)

Found solution after 9 iterations.
2.000000003372078


In [33]:
x = newton(function_bad, 0.4, 1e-05)
print(x)
x =  newton(function_bad, 100, 1e-05)
print(x)

Found solution after 8 iterations.
0.002018271330085455
Found solution after 16 iterations.
0.0019828301615753777


In [36]:
x = newton(function_superBad, 0.3, 1e-05)
print(x)
x =  newton(function_superBad, 100, 1e-05)
print(x)

Found solution after 5 iterations.
0.09964064481599835
Found solution after 32 iterations.
0.0812155626947812


In [39]:
x = newton(function_chaos, 0.8, 1e-05)
print(x)
x =  newton(function_chaos, 100, 1e-05)
print(x)

Found solution after 1 iterations.
0.7844847973396151
Exceeded maximum iterations. No solution found.
None


In [12]:
def lu(A):
    
    #Get the number of rows
    n = A.shape[0]
    
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    
    #Loop over rows
    for i in range(n):
            
        # Gaussian elminination
        
        factor = # Which are the values on the original matrix you want to get rid of
                # using Gaussian elimination?
        L[i+1:, i] = # We want to eliminate these from the original matrix
                     # but we want to keep that information in the L matrix
        U[i+1:] -= # ELIMINATE doing Gaussian elimination after saving them in 
                   # another matrix - the L matrix
        
    return L, U



In [40]:
A = np.array( [ [1, 4, 7.], [9, 5, 3], [1, 4, 8]  ]  )
n = A.shape[0]
U = A.copy()
L = np.eye(n, dtype=np.double)
print(U)
print( "----")

i = 0
factor = U[i+1:, i] / U[i, i]
L[i+1:, i] = factor

print( U[i+1:, i] )
print( U[i, i] )
print("----")
print(factor)
print( factor.shape )
print("----")
print(L)
print(factor[:, np.newaxis])
print("----")
U[i+1:] -= factor[:, np.newaxis] * U[i]
print(U)

[[1. 4. 7.]
 [9. 5. 3.]
 [1. 4. 8.]]
----
[9. 1.]
1.0
----
[9. 1.]
(2,)
----
[[1. 0. 0.]
 [9. 1. 0.]
 [1. 0. 1.]]
[[9.]
 [1.]]
----
[[  1.   4.   7.]
 [  0. -31. -60.]
 [  0.   0.   1.]]


In [44]:
A = np.array( [ [-7,11,18.], [14,-7,-3], [0,-2,1]  ] )
L, U = lu(A)
print(L)
print('----')
print(U)

[[ 1.          0.          0.        ]
 [-2.          1.          0.        ]
 [-0.         -0.13333333  1.        ]]
----
[[-7.  11.  18. ]
 [ 0.  15.  33. ]
 [ 0.   0.   5.4]]
