In [6]:
import numpy as np
import scipy.linalg as la

def genQ(i, j):
    '''
    Calculates de (i,j) entry of the generator matrix, qij
    '''
    if i == 0 and j == 0:
        qij = -1.5
    elif i == 0 and j == 1:
        qij = 1.5
    else:
        if i < 5:
            if i-1 == j:
                qij = 1
            elif i == j:
                qij = -2.5
            elif i + 1 == j:
                qij = 1.5
            else:
                qij = 0
        else:
            if i-1 == j:
                qij = 2
            elif i == j:
                qij = -3.5
            elif i+1 == j:
                qij = 1.5
            else:
                qij = 0
    
    return(qij)

In [4]:
N = 6

Q = np.zeros([N+1, N+1])

for i in range(N+1):
    for j in range(N+1):
        Q[i,j] = genQ(i, j)
        
print(Q)

[[-1.5  1.5  0.   0.   0.   0.   0. ]
 [ 1.  -2.5  1.5  0.   0.   0.   0. ]
 [ 0.   1.  -2.5  1.5  0.   0.   0. ]
 [ 0.   0.   1.  -2.5  1.5  0.   0. ]
 [ 0.   0.   0.   1.  -2.5  1.5  0. ]
 [ 0.   0.   0.   0.   2.  -3.5  1.5]
 [ 0.   0.   0.   0.   0.   2.  -3.5]]


In [9]:
N = 4

Q = np.zeros([N+1, N+1])

for i in range(N+1):
    for j in range(N+1):
        Q[i,j] = genQ(i, j)
        
print(Q)

P, L, U = la.lu(Q)
print('This is the permutation:')
print(P)


[[-1.5  1.5  0.   0.   0. ]
 [ 1.  -2.5  1.5  0.   0. ]
 [ 0.   1.  -2.5  1.5  0. ]
 [ 0.   0.   1.  -2.5  1.5]
 [ 0.   0.   0.   1.  -2.5]]
This is the permutation:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
N = 25

Q = np.zeros([N+1, N+1])

for i in range(N+1):
    for j in range(N+1):
        Q[i,j] = genQ(i, j)
        
print(Q)

P, L, U = la.lu(Q)
print('This is the permutation:')
print(P)

[[-1.5  1.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 1.  -2.5  1.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   1.  -2.5  1.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   1.  -2.5  1.5  0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   1.  -2.5  1.5  0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   2.  -3.5  1.5  0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   2.  -3.5  1.5  0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   2.  -3.5  1.5  0.   0.   0.  

In [22]:
print('With permutation')
print(Q*P)
print('L')
print(L)
print('U')
print(U)

With permutation
[[-1.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  -2.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.  -2.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -2.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  -0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   2.  -0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   2.  -0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   2.  -0.   0.

In [25]:
Qtilda = Q[1:, 1:]
la.solve( Qtilda, -1*np.ones([25, 1]) )

array([[17.99627385],
       [29.32712308],
       [36.21435591],
       [40.13917779],
       [42.08905904],
       [44.02223405],
       [45.93313406],
       [47.81433407],
       [49.65593408],
       [51.4447341 ],
       [53.16313412],
       [54.78766749],
       [56.28704531],
       [57.61954907],
       [58.72955409],
       [59.54289411],
       [59.96068081],
       [59.85106307],
       [59.03823941],
       [57.28780788],
       [54.28723249],
       [49.61979865],
       [42.72988686],
       [32.87667114],
       [19.07238351]])